[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "@ensdomains/=lib/ens-contracts/contracts/",
    "@seadrop/=lib/seadrop/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
    "utility-contracts/=lib/seadrop/lib/utility-contracts/src/",
    "ERC721A/=lib/seadrop/lib/ERC721A/contracts/",
    "solmate/=lib/seadrop/lib/solmate/src/",
    "operator-filter-registry/=lib/seadrop/lib/operator-filter-registry/src/"
]
fs_permissions = [{access = "read" , path = "./image"}]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
