[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    # OpenZeppelin
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
    
    # ENS
    "@ensdomains/=lib/ens-contracts/contracts/",
    "ens-contracts/=lib/ens-contracts/contracts/",
    
    # SeaDrop
    "@seadrop/=lib/seadrop/src/",
    "seadrop/=lib/seadrop/src/",
    
    # SeaDrop dependencies
    "utility-contracts/=lib/seadrop/lib/utility-contracts/src/",
    "ERC721A/=lib/seadrop/lib/ERC721A/contracts/",
    "ERC721A-Upgradeable/=lib/seadrop/lib/ERC721A-Upgradeable/contracts/",
    "solmate/=lib/seadrop/lib/solmate/src/",
    "operator-filter-registry/=lib/seadrop/lib/operator-filter-registry/src/",
    "murky/=lib/seadrop/lib/murky/src/",
    "create2-helpers/=lib/seadrop/lib/create2-helpers/",
    "create2-scripts/=lib/seadrop/lib/create2-helpers/script/",
    "ds-test/=lib/seadrop/lib/ds-test/src/"
]
fs_permissions = [{access = "read" , path = "./image"}]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
